<!-- {{templates/header.html}} -->
<h2> NPE Papers </h2>
<ul>
<li><a href= "papers/36.pdf"> “AN INDUCTION METHOD OF DETERMINING CONDUCTION-ZONE SIZE IN A VACUUM ARC,” V. Gorokhovsky et. al.  </a></li>
<li><a href= "papers/1.pdf"> “Advanced Thermal Barrier Coating,” R. Battacharya. SBIR Phase I Report.</a></li>
<li><a href= "papers/2.pdf"> “Advanced PVD protective coatings for SOFC interconnects,” Paul Gannon, Max Deibert, Preston White, Richard Smith, Hui Chen, Weerashinge Priyantha, Jake Lucas, Vladimir Gorokhovsky. International Journal of Hydrogen Energy.</a></li>
<li><a href= "papers/14.pdf"> “Advanced surface engineering technology for endodontic instruments and related applications,” V.Gorokhovsky, B.Heckerman, T.Browne. </a></li>
<li><a href= "papers/Balzers_Materials,_Issue_7_(1999)_DB_VG.pdf"> “Advantages of Filtered Cathodic Arc Deposition,” D.Bhat and V.Gorokhovsky. Balzers Materials, Issue 7 (1999). </a></li>
<li><a href= "papers/3.pdf"> “Application of CVD and PVD technologies to cutting tools, and evaluation of tool failure modes,” D. Bhat. Revista De La Facultad De Ingenieria(Venezuela) 13, no. 2 (1998): 15-25.</a></li>
<li><a href= "papers/27.pdf"> “Application of vacuum deposition methods to solid oxide fuel cells,” L. Pederson, P. Singh, X. Zhou. Vacuum 80 (2006) 1066–1083. </a></li>
<li><a href= "papers/16.pdf"> “Beschichtung mit gefilterten Lichtbogenverdampfern,” Erich Bergmann, Vladimir Gorokovsky. Vakuum in Forschung und Praxis 14 (2002) Nr. 6 350-354. </a></li>
<li><a href= "papers/CACVD_paper_Part_I.pdf"> “Characterization of Cascade Arc Assisted CVD Diamond Coating Technology, Part I: Plasma Processing Parameters,” V. Gorokhovsky, Surface and Coatings Technology, Number 194, May 2005. </a></li>
<li><a href= "papers/CACVD_paper_Part_II.pdf"> “Characterization of Cascade Arc Assisted CVD Diamond Coating Technology, Part II: Coating Properties and Applications,” V. Gorokhovsky. Surface and Coatings Technology, Number 194, May 2005. </a></li>
<li><a href= "papers/Lafad_PartI.pdf"> “Characterization of Large Area Filtered Arc Deposition Technology: Part I-Plasma Processing Parameters,” Vladimir I. Gorokhovsky, Rabi Bhattacharya, Deepak G. Bhat. Surface and Coatings Technology, Volume 140 (2), May 2001. </a></li>
<li><a href= "papers/Lafad_PartII.pdf"> “Characterization of Large Area Filtered Arc Deposition Technology: Part II-Coating Properties and Applications,” Gorokhovsky, V.I., Bhat, D.G., Bhattacharya, R., A.K. Rai, K. Kulkarni, R. Shivpuri. Surface and Coatings Technology, Volume 140 (3), June 2001.  </a></li>
<li><a href= "papers/SCT_Nov9'09_published.pdf"> “Characterization of thick ceramic and cermet coatings deposited by an industrial-scale LAFAD process,” V.I. Gorokhovsky. Surf. Coat. Technol. (2009) </a></li>
<li><a href= "papers/17.pdf"> “Characterization of DLC Coatings Deposited by Large Area Filtered Arc Deposition (LAFAD™) Technique,” V. Gorokhovsky, C. Hunter et. al. </a></li>
<li><a href= "papers/CrAlN_multilayers_ASM03_JMEP_preprint.pdf"> “Chromium Volatility of Coated and Uncoated Steel Interconnects for SOFCs,” C. Collins, J. Lucas, T.L. Buchanan, M. Kopczyk, A. Kayani, P.E. Gannon, M.C. Deibert, R.J. Smith, D.S. Choi, V.I. Gorokhovsky. Surface and Coatings Technology, Volume 201, Issue 7, December 2006. </a></li>
<li><a href= "papers/8.pdf"> “Chromium volatility of coated and uncoated steel interconnects for SOFCs,” C. Collins et. al. Surface & Coatings Technology 201 (2006) 4467–4470. </a></li>
<li><a href= "papers/18.pdf"> “Comparison of Carbon Coatings Deposited by Different Techniques,” V. Gorokhovsky, K.Coulter, M.Miller, R.Wei, C. Ellis, C.Engel. Presentation at ICMCTF 2010. </a></li>
<li><a href= "papers/11.pdf"> “DEVELOPMENT OF PROTECTIVE COATINGS FOR SINGLE CRYSTAL TURBINE BLADES,” Amarendra K. Rai. Report prepared for the U.S. Departement of Energy, December, 2006. </a></li>
<li><a href= "papers/35.pdf"> “DEVELOPMENT OF HARD-SOFT COATINGS FOR ENHANCED MACHINING PERFORMANCE EMPLOYING LARGE AREA FILTERED ARC DEPOSITION TECHNIQUE,” A. Rai, R. Bhattacharya. Phase II Final Report, October, 2006. </a></li>
<li><a href= "papers/Deposition_of_various_metal,_ceramic,_and_cermet_coatings.pdf"> “Deposition of Various Metal, Ceramic and Cermet Coatings by an Industrial-Scale LAFAD Process,” V. Gorokhovsky, C. Bowman, D. VanVorous, J. Wallace. JVST A, 27, 1080-1095 (2009).</a></li>
<li><a href= "papers/Wear_paper_TiCr-TiCrN+TiBC_publishedMay'08.pdf"> “Deposition and Characterization of Hybrid Filtered Arc-Magnetron Multilayer Nanocomposite Cermet Coatings for Advanced Tribological Applications,” V. Gorokovsky, C. Bowman, P.E. Gannon, D. VanVorous, J. Hu, C. Muratore, A.A., Voevodin, Y.S. Kang. Wear 265 (2008) 741-755. </a></li>
<li><a href= "papers/15.pdf"> “Deposition and Evaluation of Protective PVD Coatings on Ferritic Stainless Steel SOFC Interconnects,” V. Gorokhovsky et. al. Journal of The Electrochemical Society, 153(10) A1886-A1893 (2006). </a></li>
<li><a href= "papers/NADCA_paper_1998.pdf"> “Development of a Coating for Wear and Cracking Prevention in Die-Casting Dies by the Filtered Cathodic Arc Process,” D.Bhat, V.Gorokhovsky, R.Bhattacharya, R.Shivpuri, K.Kulkarni. Proceeding of NADCA meeting, Cleveland, OH, 1999. </a></li>
<li><a href= "papers/25.pdf"> “Development of a Coating for Wear and Cracking Prevention in Die-Casting Dies by the Filtered Cathodic Arc Process,” D. Bhat, V. Gorokhovsky, R. Bhattacharya. </a></li>
<li><a href= "papers/29.pdf"> “Development of a Coating for Wear and Cracking Prevention in Die-Casting Dies by the Filtered Cathodic Arc Process,” D. Bhat, V. Gorokhovsky, R. Bhattacharya. North American Die Casting Association. </a></li>
<li><a href= "papers/10.pdf"> “Dissolution and soldering behavior of nitrided hot working steel with multilayer LAFAD PVD coatings,” V. Joshi et. al. Surface and Coatings Technology 146–147 (2001) 338–343. </a></li>
<li><a href= "papers/12.pdf"> “Dissolution and soldering behavior of nitrided hot working steel with multilayer LAFAD PVD coatings,” V. Joshi et. al. Surface and Coatings Technology 146–147 (2001) 338–343. </a></li>
<li><a href= "papers/7.pdf"> “Distributed Arc Sources,” V. Gorokhovsky, V. Polistchook, I. Yartsev, J. Glaser. Coatings from the Vacuum Arc (423). </a></li>
<li><a href= "papers/Evaluation_of_SOFC_Coatings.pdf"> “Evaluation of SOFC Interconnects Made of Ferritic Steels with Nano-Structured Oxi-Ceramic Protective Coatings Deposited by the LAFAD Process,” V. I. Gorokhovsky,  P. E. Gannon,  J. Wallace,  D. VanVorous,  C. Bowman, M. C. Deibert,  and R. J. Smith.  Journal of The Electrochemical Society, 158 (5) B526-B535 (2011). </a></li>
<li><a href= "papers/34.pdf"> “Indentation hardness evaluation of cathodic arc deposited thin hard coatings,” J. Tuck, A. Korsunsky, D. Bhat, S. Bull. Surface and Coatings Technology 139 (2001) 63-74. </a></li>
<li><a href= "papers/CH4_fraction_on_composition_of_LAFAD_TiCN_Vacuum.pdf"> “Influence of CH4 fraction on the composition, structure, and internal stress of the TiCN coatings deposited by LAFAD technique,” Y.H.Cheng, T.Brown, B.Heckerman. Vacuum 85 (2010) 89-94 </a></li>
<li><a href= "papers/Influence_of_Si_content_on_nanocomposite_TiSiN_by_LAFAD.pdf"> “Influence of Si Content on the Structure and Internal Stress of the Nanocomposite TiSiN Coatings Deposited by Large Area Filtered Arc Deposition,” Y.H. Cheng, T. Browne, B. Heckerman, J.C. Jiang, E.I. Meletis, C. Bowman, and V.I. Gorokhovsky. J Phys D: Appl Phys 42 125415 (2009). </a></li>
<li><a href= "papers/5.pdf"> “Influence of the C content on the mechanical and tribological properties of the TiCN coatings deposited by LAFAD technique,” Y. Cheng, T. Browne, B. Heckerman, E. Meletis. Surface & Coatings Technology 205 (2011) 4024–4029. </a></li>
<li><a href= "papers/6.pdf"> “Influence of CH4 fraction on the composition, structure, and internal stress of the TiCN coatings deposited by LAFAD technique,” Y. Cheng, T. Browne, B. Heckerman. Vacuum 85 (2010) 89-94. </a></li>
<li><a href= "papers/19.pdf"> “Influence of Si content on the structure and internal stress of the nanocomposite TiSiN coatings deposited by large area filtered arc deposition,” Y. Cheng et. al. 2009 J. Phys. D: Appl. Phys. 42 125415. </a></li>
<li><a href= "papers/20.pdf"> “Internal stresses in TiN/Ti multilayer coatings deposited by large area filtered arc deposition,” Y. Cheng et. al. JOURNAL OF APPLIED PHYSICS 104, 093502 (2008). </a></li>
<li><a href= "papers/9.pdf"> “Investigation of the current distribution at the anode of a vacuum arc in a longitudinal magnetic field,” V. Gorokhovsky, V. Elovikov. Sov. Phys. Tech. Phys. 32(11), November 1987. </a></li>
<li><a href= "papers/Ion_treatment_by_low_pressure_arc_PI_surface_engineering.pdf"> “Ion treatment by low pressure arc plasma immersion surface engineering processes,” V. Gorokhovsky, P. Del Bel Belluz. Surface and Coatings Technology Volume 215, 25 January 2013, Pages 431–439. </a></li>
<li><a href= "papers/21.pdf"> “Ion treatment by low pressure arc plasma immersion surface engineering processes,” V. Gorokhovsky, P. Del Bel Belluz. Surface & Coatings Technology 215 (2013) 431–439. </a></li>
<li><a href= "papers/GT2009-59391.pdf"> “LAFAD Hard Ceramic and Cermet Coatings for Erosion Protection of Turbomachinery Components,” Vladimir Gorokhovsky, Chris Bowman, John Wallace, Dave VanVorous, John O’Keefe, Victor Champagne, Marc Pepi, Widen Tabakoff. GT2009-59391, Proceedings of ASME Turbo Expo 2009: Power for Land, Sea and Air GT2009 June 8-12, 2009, Orlando, Florida, USA. </a></li>
<li><a href= "papers/LAFAD_review_ICACC'10_ACeR.pdf"> “LAFAD-Assisted Plasma Surface Engineering Processes for Wear and Corrosion Protection: A Review,” V. Gorokhovsky. In Advanced Ceramic Coatings and Interfaces V: Ceramic Engineering and Science Proceedings, Vol. 31, No. 3, Ed. by Dongming Zhu,  Hua-Tay Lin, 204 pg.  </a></li>
<li><a href= "papers/LARGE_AREA_FILTERED_ARC_DEPOSITION_OF_CARBON_AND_BORON.pdf"> “LARGE AREA FILTERED ARC DEPOSITION OF CARBON AND BORON BASED HARD COATINGS,” Rabi Bhattaccharia. Final Report Prepared for THE U.S. DEPARTMENT OF ENERGY Contract No. DE-FG02-99ER82911 for For Period September 4, 1999 – September 5, 2003, UES, Inc., Dayton OH. </a></li>
<li><a href= "papers/LAFAD_presentation_ICMCTF'07.pdf"> “Large Area Filtered Plasma Deposition Technology and Applications,” V. Gorokhovsky. Presentation to ICMCTF 2007. </a></li>
<li><a href= "papers/22.pdf"> “Large Area Filtered Plasma Deposition Technology and Applications,” V. Gorokhovsky. Presentation to ICMCTF 2007. </a></li>
<li><a href= "papers/23.pdf"> “Mechanical and tribological properties of nanocomposite TiSiN coatings,” Y.H. Cheng, T. Browne, B. Heckerman, E. Meletis. Surface & Coatings Technology 204 (2010) 2123–2129. </a></li>
<li><a href= "papers/24.pdf"> “Multiphase Nano-Composite Coatings for Achieving Energy Optimization,” J. Nainaparampil. Technical report. </a></li>
<li><a href= "papers/Oct20.pdf"> “Nano-Composite Coatings for F-35 LiftFan Gears.” </a></li>
<li><a href= "papers/26.pdf"> “Nanocomposite Tribological Corrosion Resistant Coating for Robust Bearings and Gears,” V. Gorokhovsky, C. Bowman. Phase II SBIR Final Report, February, 2009. </a></li>
<li><a href= "papers/Kayani_ASM04_SCT2006_oxidation_CrAlON_FAD_coatings.pdf"> “Oxidation Studies of CrAlON Nanolayered Coatings on Steel Plates,” A. Kayani, R.J. Smith, S. Teintze, M. Kopczyk, P.E. Gannon, M.C. Deibert, V.I. Gorokhovsky, V. Shutthanandan. Surface and Coatings Technology, Volume 201, Issues 3-4, October 2006. </a></li>
<li><a href= "papers/rotated_paper.pdf"> “Principles and Applications of Vacuum Arc Plasma-assisted Surface Engineering Technologies,” V. Gorokhovsky, D. Bhat. In Proceedings of the GOI-UNDP International Workshop on Surface Engineering and Coatings, Bangalore, India, ed. by I. Rajagopal, K.S. Rajam, R.V. Krishnan, Allied Publishers, Ltd., Mumbai, India, 1999. </a></li>
<li><a href= "papers/31.pdf"> “Processes in plasma arc installation for vacuum coating depositions, Part 1: Plasma generation,” V. Gorokhovsky. Surface and Coatings Technology, 61 (1993) 101-107. </a></li>
<li><a href= "papers/32.pdf"> “Processes in plasma arc installation for vacuum coating depositions, Part 2: Plasma propogation,” V. Gorokhovsky. Surface and Coatings Technology, 61 (1993) 108-114. </a></li>
<li><a href= "papers/30.pdf"> “Soldering and Ejection Behavior of Duplex and Multilayer Filtered Arc PVD Coatings,” R. Shivpuri, V. Joshi, A. Srivastava, R. Bhattacharya, S. Dixit, D. Bhat. North American Die Casting Association. </a></li>
<li><a href= "papers/33.pdf"> “Superhard i-C coatings used in complex processes of surface strengthening of tools and machine parts,” N. Novikov, V. Gorokhovsky, B. Uryukov. Surface and Coatings Technology, 47(1991) 770—791. </a></li>
<li><a href= "papers/28.pdf"> “THE EXPANSION OF THE EROSION ARC PLASMA FLUX INTO VACUUM,” B. Uryukov, V. Gorokhovsky, V. Elovikov. Institute for Superhard Materials of the Ukrainian Academy of Sciences, Kiev, USSR. </a></li>
<li><a href= "papers/Periodontal_SCT_200(2006)5614-5630.pdf"> “The Effect of Multilayer Filtered Arc Coatings on Mechanical Properties, Corrosion Resistance, and Performance of Periodontal Dental Instruments,” Vladimir Gorokhovsky, Brad Heckerman, Philip Watson, Nicholas Bekesch. Surface and Coatings Technology, Volume 200, Issues 18-19, May 2006. </a></li>
<li><a href= "papers/13.pdf"> “The system for depositing hard diamond-like films onto complex-shaped machine elements in an r.f. arc plasma,” S. Mitura, Z. Has, V. Gorokhovsky. Surface and Coatings Technology, 47 (1991) 106-112. </a></li>
<li><a href= "papers/Tribo_paper_Part_I_SCT.pdf"> “Tribological Performance of Hybrid Filtered Arc-Magnetron Coatings, Part I,” V. Gorokhovsky, C. Bowman, P. Gannon, D. VanVorous, A.A. Voevodin, A. Rutkowski, C. Muratore, R.J. Smith, A. Kayani, D. Gelles, V. Shutthanandan, B.G. Trusov. Surface and Coatings Technology, Volume 201, Issue 6, December 2006. </a></li>
<li><a href= "papers/Tribo_paper_part_II_SCT_V201-14_April-2007.pdf"> “Tribological Performance of Hybrid Filtered Arc-Magnetron Coatings, Part II,” Vladimir Gorokhovsky, Chris Bowman, Paul Gannon, Dave VanVorous, Andrey Voevodin, A. Rutkowski. Surface and Coatings Technology, Number 201, 2007. </a></li>
<li><a href= "papers/CrAlN_multilayers_ASM03_JMEP_preprint.pdf"> “Using CrAlN multilayer coatings to improve oxidation resistance of steel interconnects for solid oxide fuel cells,” R.J. Smith, C. Tripp, A. Knospe, C.V. Ramana, A. Kayani, Vladimir Gorokhovsky, V. Shutthanandan, D.S.Gelles.  Journal of Materials Engineering and Performance 13(3) (2004) 295-302. </a></li>
<li><a href= "papers/4.pdf"> “Vacuum Metal Web Coating with Cermets,” V. Gorokhovsky. Proceedings of the Fourth International Conference on Vacuum Web Coating; Reno, Nevada, 1990. </a></li>
</ul>

<!-- {{templates/footer.html}} -->
