<!-- {{templates/header.html}} -->

<div class="col-sm-12">
<p class="text-justify">
  NPE’s unidirectional large-area dual filtered arc deposition (LAFAD™) surface engineering metal vapor plasma sources

  use a rectangular plasma duct chamber with two rectangular coils installed in opposite sides, as schematically illustrated
  <span class="active-word-parent">
    here.
    <img class="active-word-child" src="PVD/lafad-1.png">
  </span>
  Two cathodic arc sources

  with rectangular or circular (billet) targets are installed in the side walls of the plasma duct chamber, surrounded by rectangular focusing and deflecting coils.

  A quasi-flat deflecting magnetic field configuration significantly reduces plasma losses in the direction close to the plasma duct walls, allowing for the dual metal vapor plasma jets to propagate freely along the magnetic field lines to reach remote parts of the deposition chamber as illustrated
  <span class="active-word-parent">
    here.
    <video autoplay loop class="active-word-child">
      <source src="PVD/lafad-2.mp4" type="video/mp4">
    </video>
  </span>
  This results in a dramatic increase of output arc current,
  which can exceed more than 10 amperes for an input current of 300 amperes for two incorporated cathodic arc sources. At the same time ionization rate of

  gaseous plasma components within magnetized arc plasma column can reach more than 30%. As a result the deposition rate of 100% ionized metal vapor plasma generated by an LAFAD™ source has been

  found to be almost the same or even greater than that of direct (not-filtered) cathodic arc source. At the same time the macroparticles and neutral atoms emitted from the cathode target are captured by the baffles installed along plasma duct walls not occupied by vapor plasma sources, as illustrated
  <span class="active-word-parent">
    here.
    <video height="400px" autoplay loop class="active-word-child">
      <source src="PVD/lafad-3.mp4" type="video/mp4">
    </video>
  </span>
  This advanced filtered design provides practically macro-
  particle free coatings in large areas, ranging from about 250 mm in width to heights on the order of 300 mm to 3 m or more. Typical target utilization rate for a

  cylindrical primary cathodic arc sources of the LAFAD™ dual filtered arc source, utilizing round targets is as high as 80-90% for primary cathodic arc sources

  with cylindrical (billet) targets, and up to 40% in case of using the planar or rotary primary cathodic arc sources with large rectangular or tubular targets.

  In addition the vacuum arc cathode is also a theoretically unlimited electron emitter, thereby providing an efficient source of high-density electron current. In

  this mode, it facilitates the generation of a uniform, high-density plasma cloud in the coating deposition chamber. This results in a "plasma-immersion"

  environment, which provides a uniform condition for plasma ion etching, ion nitriding, low energy ion implantation, plasma-assisted chemical vapor deposition

  and multilayer filtered arc PVD coatings in a single vacuum cycle.
</p>
</div>

  <!-- {{templates/footer.html}} -->
